platform :ios, ‘8.0’

use_frameworks!

target ‘project’ do
    
pod 'libextobjc'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh'
pod 'YYKit'


#pod 'SVProgressHUD'
#pod 'GPUImage'
#pod 'SKPanoramaView'

#pod 'Cordova'
#pod 'FMDB'
#pod 'DZNEmptyDataSet'
#pod 'BmobSDK'
#pod 'CocoaLumberjack', '~> 2.2.0'
#pod 'pop', '~> 1.0.7'
#pod 'UMengAnalytics', '~> 3.6.6'


#以下是LearnCloud专区
# 数据存储、短信、云引擎调用等基础服务模块
#pod 'AVOSCloud'
# 实时通信模块
#pod 'AVOSCloudIM'
# 错误报告模块
#pod 'AVOSCloudCrashReporting'

#pod 'Masonry'
#pod 'JSONModel'
#pod 'SDWebImage'
#pod 'IQKeyboardManager'
#pod 'SDCycleScrollView'

#pod 'BaiduMapKit'
#pod 'AlipaySDKHum', '~> 15.0.8.1'
#pod 'BPushSDK', '~> 1.4.4'

#pod 'ShareSDK3'
#pod 'MOBFoundation'
#pod 'ShareSDK3/ShareSDKUI'
#pod 'ShareSDK3/ShareSDKPlatforms/QQ'
#pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
#pod 'ShareSDK3/ShareSDKPlatforms/WeChat'

#pod 'HyphenateLite_CN'



#在安装和更新时，加参数的命令如下：
#pod install --verbose --no-repo-update
#pod update --verbose --no-repo-update








end
